server.port: 8081
spring.kafka:
  consumer:
    bootstrapservers: 0.0.0.0:9092
    group-id: group-1
    key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
